// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// This file is auto-generated from config/Domains.json
// Do not edit this file directly.

/**
 * Well-known Azure service domains for internal use.
 */

/**
 * Azure Key Vault service domains across all public Azure environments.
 */
export const _azureKeyVaultDomains: readonly string[] = [
    "vault.azure.net",
    "managedhsm.azure.net",
    "vault.azure.cn",
    "managedhsm.azure.cn",
    "vault.usgovcloudapi.net",
    "managedhsm.usgovcloudapi.net",
];

/**
 * Azure Storage service domains across all public Azure environments.
 */
export const _azureStorageDomains: readonly string[] = [
    "blob.core.windows.net",
    "web.core.windows.net",
    "dfs.core.windows.net",
    "file.core.windows.net",
    "queue.core.windows.net",
    "table.core.windows.net",
    "blob.storage.azure.net",
    "web.storage.azure.net",
    "dfs.storage.azure.net",
    "file.storage.azure.net",
    "queue.storage.azure.net",
    "table.storage.azure.net",
    "blob.core.usgovcloudapi.net",
    "web.core.usgovcloudapi.net",
    "dfs.core.usgovcloudapi.net",
    "file.core.usgovcloudapi.net",
    "queue.core.usgovcloudapi.net",
    "table.core.usgovcloudapi.net",
    "blob.core.chinacloudapi.cn",
    "web.core.chinacloudapi.cn",
    "dfs.core.chinacloudapi.cn",
    "file.core.chinacloudapi.cn",
    "queue.core.chinacloudapi.cn",
    "table.core.chinacloudapi.cn",
];
