// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Auto-generated from IPAddressRanges.json
// Do not edit this file manually

namespace Microsoft.Security.AntiSSRF
{
    /// <summary>
    /// Static IP address ranges for AntiSSRF protection
    /// </summary>
    public static class IPAddressRanges
    {
        public static readonly string[] amt = { "192.52.193.0/24", "2001:3::/32" };
        public static readonly string[] as112 = { "192.31.196.0/24", "192.175.48.0/24", "2001:4:112::/48", "2620:4f:8000::/48" };
        public static readonly string[] benchmarking = { "198.18.0.0/15", "2001:2::/48" };
        public static readonly string[] deprecated = { "192.88.99.0/24", "2001:10::/28" };
        public static readonly string[] detsPrefix = { "2001:30::/28" };
        public static readonly string[] discardOnly = { "100::/64" };
        public static readonly string[] documentation = { "192.0.2.0/24", "198.51.100.0/24", "203.0.113.0/24", "2001:db8::/32", "3fff::/20" };
        public static readonly string[] dummy = { "192.0.0.8/32", "100:0:0:1::/64" };
        public static readonly string[] ietfProtocol = { "192.0.0.0/24", "2001::/23" };
        public static readonly string[] imds = { "169.254.169.254/32" };
        public static readonly string[] ipv4Ipv6Translat = { "64:ff9b::/96", "64:ff9b:1::/48" };
        public static readonly string[] ipv4ServiceContinuity = { "192.0.0.0/29" };
        public static readonly string[] broadcast = { "255.255.255.255/32" };
        public static readonly string[] linkLocal = { "169.254.0.0/16", "fe80::/10" };
        public static readonly string[] loopback = { "127.0.0.0/8", "::1/128" };
        public static readonly string[] multicast = { "224.0.0.0/4", "ff00::/8" };
        public static readonly string[] orchidv2 = { "2001:20::/28" };
        public static readonly string[] privateUse = { "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16" };
        public static readonly string[] reserved = { "240.0.0.0/4" };
        public static readonly string[] sharedAddressSpace = { "100.64.0.0/10" };
        public static readonly string[] siteLocal = { "fec0::/10" };
        public static readonly string[] sixto4 = { "2002::/16" };
        public static readonly string[] srv6Sid = { "5f00::/16" };
        public static readonly string[] teredo = { "2001::/32" };
        public static readonly string[] uniqueLocal = { "fc00::/7" };
        public static readonly string[] unspecified = { "0.0.0.0/8", "::/128" };
        public static readonly string[] wireserver = { "168.63.129.16/32" };
        public static readonly string[] recommendedV1 = { "0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "168.63.129.16/32", "169.254.0.0/16", "172.16.0.0/12", "192.0.0.0/24", "192.0.2.0/24", "192.31.196.0/24", "192.52.193.0/24", "192.88.99.0/24", "192.168.0.0/16", "192.175.48.0/24", "198.18.0.0/15", "198.51.100.0/24", "203.0.113.0/24", "224.0.0.0/4", "240.0.0.0/4", "::1/128", "::/128", "64:ff9b::/96", "64:ff9b:1::/48", "100::/64", "100:0:0:1::/64", "2001::/23", "2001:db8::/32", "2002::/16", "2620:4f:8000::/48", "3fff::/20", "5f00::/16", "fc00::/7", "fe80::/10", "fec0::/10", "ff00::/8" };

        /// <summary>
        /// recommendedLatest always points to the latest version
        /// </summary>
        public static readonly string[] recommendedLatest = recommendedV1;
    }
}
