#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Script to build IPAddressRanges.cs from IPAddressRanges.json
# Only includes cidr ranges as C# static readonly arrays

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JSON_FILE="$SCRIPT_DIR/../config/IPAddressRanges.json"
CS_FILE="$SCRIPT_DIR/../csharp/config/IPAddressRanges.cs"

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed. Install with: brew install jq"
    exit 1
fi

# Check if JSON file exists
if [[ ! -f "$JSON_FILE" ]]; then
    echo "Error: IPAddressRanges.json not found in $SCRIPT_DIR"
    exit 1
fi

# Create directory if it doesn't exist
mkdir -p "$(dirname "$CS_FILE")"

# Generate C# file
cat > "$CS_FILE" << 'EOF'
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Auto-generated from IPAddressRanges.json
// Do not edit this file manually

namespace Microsoft.Security.AntiSSRF
{
    /// <summary>
    /// Static IP address ranges for AntiSSRF protection
    /// </summary>
    public static class IPAddressRanges
    {
EOF

# Generate individual field declarations
jq -r '
  to_entries 
  | map(select(.key != "_sources" and .value.standaloneVariable == true)) 
  | .[] 
  | "        public static readonly string[] " + .key + " = { " + (.value.cidr | map("\"" + . + "\"") | join(", ")) + " };"
' "$JSON_FILE" >> "$CS_FILE"

# Add recommendedLatest property that matches recommendedV1
cat >> "$CS_FILE" << 'EOF'

        /// <summary>
        /// recommendedLatest always points to the latest version
        /// </summary>
        public static readonly string[] recommendedLatest = recommendedV1;
EOF



# Close the class and namespace
cat >> "$CS_FILE" << 'EOF'
    }
}
EOF

echo "Successfully generated $CS_FILE"