#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Generates nodejs/src/Helpers/Domains.ts from config/Domains.json

set -e

# Path to the domains configuration file
DOMAINS_JSON="config/Domains.json"
OUTPUT_FILE="nodejs/src/Helpers/Domains.ts"

# Ensure the output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed. Please install jq to continue."
    exit 1
fi

# Check if domains.json exists
if [[ ! -f "$DOMAINS_JSON" ]]; then
    echo "Error: $DOMAINS_JSON not found"
    exit 1
fi

# Extract domains from JSON for TypeScript/JavaScript format
AZURE_KEYVAULT_DOMAINS=$(jq -r '.azureKeyVault.domains[]' "$DOMAINS_JSON" | sed 's/^/    "/' | sed 's/$/"/' | tr '\n' ',' | sed 's/,$//')
AZURE_STORAGE_DOMAINS=$(jq -r '.azureStorage.domains[]' "$DOMAINS_JSON" | sed 's/^/    "/' | sed 's/$/"/' | tr '\n' ',' | sed 's/,$//')

# Generate TypeScript file
cat > "$OUTPUT_FILE" << 'EOF'
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// This file is auto-generated from config/Domains.json
// Do not edit this file directly.

/**
 * Well-known Azure service domains for internal use.
 */

/**
 * Azure Key Vault service domains across all public Azure environments.
 */
export const _azureKeyVaultDomains: readonly string[] = [
EOF

# Add Azure Key Vault domains
echo "$AZURE_KEYVAULT_DOMAINS" | tr ',' '\n' | while IFS= read -r line; do
    if [[ -n "$line" ]]; then
        echo "$line," >> "$OUTPUT_FILE"
    fi
done

cat >> "$OUTPUT_FILE" << 'EOF'
];

/**
 * Azure Storage service domains across all public Azure environments.
 */
export const _azureStorageDomains: readonly string[] = [
EOF

# Add Azure Storage domains
echo "$AZURE_STORAGE_DOMAINS" | tr ',' '\n' | while IFS= read -r line; do
    if [[ -n "$line" ]]; then
        echo "$line," >> "$OUTPUT_FILE"
    fi
done

cat >> "$OUTPUT_FILE" << 'EOF'
];
EOF

echo "Generated $OUTPUT_FILE successfully"