#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Script to build IPAddressRanges.ts from IPAddressRanges.json
# Generates a TypeScript class with static readonly properties

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JSON_FILE="$SCRIPT_DIR/../config/IPAddressRanges.json"
TS_FILE="$SCRIPT_DIR/../nodejs/src/IPAddressRanges.ts"

# Check if jq is available
if ! command -v jq &> /dev/null; then
  echo "Error: jq is required but not installed."
  echo "Install on WSL/Ubuntu: sudo apt-get update && sudo apt-get install -y jq"
  echo "Install on macOS: brew install jq"
    exit 1
fi

# Check if JSON file exists
if [[ ! -f "$JSON_FILE" ]]; then
    echo "Error: IPAddressRanges.json not found in $SCRIPT_DIR"
    exit 1
fi

# Generate TypeScript file
echo "// Copyright (c) Microsoft Corporation." > "$TS_FILE"
echo "// Licensed under the MIT License." >> "$TS_FILE"
echo "" >> "$TS_FILE"
echo "// Auto-generated from IPAddressRanges.json" >> "$TS_FILE"
echo "// Do not edit this file manually" >> "$TS_FILE"
echo "" >> "$TS_FILE"
echo "/**" >> "$TS_FILE"
echo " * Static IP address ranges for AntiSSRF protection" >> "$TS_FILE"
echo " */" >> "$TS_FILE"
echo "export class IPAddressRanges {" >> "$TS_FILE"

# Generate individual property declarations
jq -r '
  to_entries 
  | map(select(.key != "_sources" and .value.standaloneVariable == true)) 
  | .[] 
  | "    public static readonly " + .key + ": string[] = [" + (.value.cidr | map("\"" + . + "\"") | join(", ")) + "];"
' "$JSON_FILE" >> "$TS_FILE"

# Add recommendedLatest property that matches recommendedV1
echo "" >> "$TS_FILE"
echo "    /**" >> "$TS_FILE"
echo "     * recommendedLatest always points to the latest version" >> "$TS_FILE"
echo "     */" >> "$TS_FILE"
echo "    public static readonly recommendedLatest: string[] = IPAddressRanges.recommendedV1;" >> "$TS_FILE"

# Close the class
echo "}" >> "$TS_FILE"

echo "Successfully generated $TS_FILE"